/* List of countries, with: - Conversion factor - Protein consumption - Bod per day (IPCC TABLE 6.4)
   UPDATED TABLE (20/5/2021)
   2: https://www.eib.org/attachments/strategies/eib_project_carbon_footprint_methodologies_en.pdf
   3: IPCC, 2006, Guidelines for National Greenhouse Gas Inventories Volume 5 Waste
   4: currencies: https://www.countries-ofthe-world.com/world-currencies.html (checked on 2020-12-10)
   conv_kwh_co2 -> gCO2/kWh (converted to kg after the definition of the table)
   prot_con     -> kg/person/year
   bod_pday     -> g/person/day
*/

let Countries = {
    "AFG": {name: "Afghanistan", conv_kwh_co2: 300},
    "ALA": {name: "Åland Islands"},
    "ALB": {name: "Albania", conv_kwh_co2: 16},
    "DZA": {name: "Algeria", conv_kwh_co2: 498},
    "ASM": {name: "American Samoa"},
    "AND": {name: "Andorra"},
    "AGO": {name: "Angola", conv_kwh_co2: 613},
    "AIA": {name: "Anguilla"},
    "ATA": {name: "Antarctica"},
    "ATG": {name: "Antigua and Barbuda", conv_kwh_co2: 693},
    "ARG": {name: "Argentina", conv_kwh_co2: 497},
    "ARM": {name: "Armenia", conv_kwh_co2: 339},
    "ABW": {name: "Aruba"},
    "AUS": {name: "Australia", conv_kwh_co2: 646},
    "AUT": {name: "Austria", conv_kwh_co2: 173},
    "AZE": {name: "Azerbaijan", conv_kwh_co2: 488},
    "BHS": {name: "Bahamas", conv_kwh_co2: 669},
    "BHR": {name: "Bahrain"},
    "BGD": {name: "Bangladesh", conv_kwh_co2: 565},
    "BRB": {name: "Barbados", conv_kwh_co2: 684},
    "BLR": {name: "Belarus", conv_kwh_co2: 390},
    "BEL": {name: "Belgium", conv_kwh_co2: 227},
    "BLZ": {name: "Belize", conv_kwh_co2: 461},
    "BEN": {name: "Benin", conv_kwh_co2: 705},
    "BMU": {name: "Bermuda"},
    "BTN": {name: "Bhutan"},
    "BOL": {name: "Bolivia", conv_kwh_co2: 529},
    "BIH": {name: "Bosnia and Herzegovina", conv_kwh_co2: 1231},
    "BWA": {name: "Botswana", conv_kwh_co2: 1480},
    "BVT": {name: "Bouvet Island"},
    "BRA": {name: "Brazil", conv_kwh_co2: 296},
    "IOT": {name: "British Indian Ocean Territory"},
    "BRN": {name: "Brunei Darussalam"},
    "BGR": {name: "Bulgaria", conv_kwh_co2: 813},
    "BFA": {name: "Burkina Faso", conv_kwh_co2: 734},
    "BDI": {name: "Burundi"},
    "KHM": {name: "Cambodia", conv_kwh_co2: 820},
    "CMR": {name: "Cameroon", conv_kwh_co2: 397},
    "CAN": {name: "Canada", conv_kwh_co2: 286},
    "CPV": {name: "Cape Verde", conv_kwh_co2: 699},
    "CKY": {name: "Cayman Islands"},
    "CAF": {name: "Central African Republic", conv_kwh_co2: 332},
    "TCD": {name: "Chad", conv_kwh_co2: 741},
    "CHL": {name: "Chile", conv_kwh_co2: 532},
    "CHN": {name: "China", conv_kwh_co2: 775},
    "CXR": {name: "Christmas Island"},
    "CCK": {name: "Cocos (Keeling) Islands"},
    "COL": {name: "Colombia", conv_kwh_co2: 309},
    "COM": {name: "Comoros"},
    "COG": {name: "Congo", conv_kwh_co2: 472},
    "COD": {name: "Congo, The Democratic Republic of the"},
    "COK": {name: "Cook Islands"},
    "CRI": {name: "Costa Rica", conv_kwh_co2: 215},
    "CIV": {name: "Cote D'Ivoire", conv_kwh_co2: 530},
    "HRV": {name: "Croatia", conv_kwh_co2: 327},
    "CUB": {name: "Cuba", conv_kwh_co2: 755},
    "CYP": {name: "Cyprus", conv_kwh_co2: 630},
    "CZE": {name: "Czech Republic", conv_kwh_co2: 794},
    "DNK": {name: "Denmark", conv_kwh_co2: 384},
    "DJI": {name: "Djibouti", conv_kwh_co2: 735},
    "DMA": {name: "Dominica", conv_kwh_co2: 702},
    "DOM": {name: "Dominican Republic", conv_kwh_co2: 566},
    "ECU": {name: "Ecuador", conv_kwh_co2: 586},
    "EGY": {name: "Egypt", conv_kwh_co2: 483},
    "SLV": {name: "El Salvador", conv_kwh_co2: 491},
    "GNQ": {name: "Equatorial Guinea"},
    "ERI": {name: "Eritrea"},
    "EST": {name: "Estonia", conv_kwh_co2: 1049},
    "ETH": {name: "Ethiopia", conv_kwh_co2: 16},
    "FLK": {name: "Falkland Islands (Malvinas)"},
    "FRO": {name: "Faroe Islands"},
    "FJI": {name: "Fiji", conv_kwh_co2: 631},
    "FIN": {name: "Finland", conv_kwh_co2: 241},
    "FRA": {name: "France", conv_kwh_co2: 124},
    "GUF": {name: "French Guiana"},
    "PYF": {name: "French Polynesia", conv_kwh_co2: 661},
    "ATF": {name: "French Southern Territories"},
    "GAB": {name: "Gabon", conv_kwh_co2: 634},
    "GMB": {name: "Gambia", conv_kwh_co2: 736},
    "GEO": {name: "Georgia", conv_kwh_co2: 278},
    "DEU": {name: "Germany", conv_kwh_co2: 596},
    "GHA": {name: "Ghana", conv_kwh_co2: 509},
    "GIB": {name: "Gibraltar"},
    "GRC": {name: "Greece", conv_kwh_co2: 611},
    "GRL": {name: "Greenland"},
    "GRD": {name: "Grenada", conv_kwh_co2: 704},
    "GLP": {name: "Guadeloupe"},
    "GUM": {name: "Guam"},
    "GTM": {name: "Guatemala", conv_kwh_co2: 564},
    "GGY": {name: "Guernsey"},
    "GIN": {name: "Guinea", conv_kwh_co2: 677},
    "GNB": {name: "Guinea-Bissau", conv_kwh_co2: 741},
    "GUY": {name: "Guyana", conv_kwh_co2: 723},
    "HTI": {name: "Haiti", conv_kwh_co2: 829},
    "HMD": {name: "Heard Island and Mcdonald Islands"},
    "VAT": {name: "Holy See (Vatican City State)"},
    "HND": {name: "Honduras", conv_kwh_co2: 654},
    "HKG": {name: "Hong Kong", conv_kwh_co2: 576},
    "HUN": {name: "Hungary", conv_kwh_co2: 318},
    "ISL": {name: "Iceland", conv_kwh_co2: 16},
    "IND": {name: "India", conv_kwh_co2: 878},
    "IDN": {name: "Indonesia", conv_kwh_co2: 677},
    "IRN": {name: "Iran, Islamic Republic Of", conv_kwh_co2: 570},
    "IRQ": {name: "Iraq", conv_kwh_co2: 1159},
    "IRL": {name: "Ireland", conv_kwh_co2: 328},
    "IMN": {name: "Isle of Man"},
    "ISR": {name: "Israel", conv_kwh_co2: 391},
    "ITA": {name: "Italy", conv_kwh_co2: 359},
    "JAM": {name: "Jamaica", conv_kwh_co2: 672},
    "JPN": {name: "Japan", conv_kwh_co2: 456},
    "JEY": {name: "Jersey"},
    "JOR": {name: "Jordan", conv_kwh_co2: 607},
    "KAZ": {name: "Kazakhstan", conv_kwh_co2: 817},
    "KEN": {name: "Kenya", conv_kwh_co2: 478},
    "KIR": {name: "Kiribati", conv_kwh_co2: 721},
    "PRK": {name: "Democratic People's Republic of Korea", conv_kwh_co2: 622},
    "KOR": {name: "Korea, Republic of", conv_kwh_co2: 442},
    "XXK": {name: "Kosovo"},
    "KWT": {name: "Kuwait", conv_kwh_co2: 578},
    "KGZ": {name: "Kyrgyzstan", conv_kwh_co2: 218},
    "LAO": {name: "Lao People's Democratic Republic"},
    "LVA": {name: "Latvia", onv_kwh_co2: 245},
    "LBN": {name: "Lebanon", conv_kwh_co2: 697},
    "LSO": {name: "Lesotho", conv_kwh_co2: 16},
    "LBR":{name: "Liberia", conv_kwh_co2: 574},
    "LBY": {name: "Libyan Arab Jamahiriya"},
    "LIE": {name: "Liechtenstein"},
    "LTU": {name: "Lithuania", conv_kwh_co2: 302},
    "LUX": {name: "Luxembourg", conv_kwh_co2: 301},
    "MAC": {name: "Macao", conv_kwh_co2: 370},
    "MKD": {name: "Macedonia, The Former Yugoslav Republic of", conv_kwh_co2: 921},
    "MDG": {name: "Madagascar"},
    "MWI":{name: "Malawi", conv_kwh_co2: 16},
    "MYS": {name: "Malaysia", conv_kwh_co2: 551},
    "MDV":{name: "Maldives", conv_kwh_co2: 703},
    "MLI":{name: "Mali", conv_kwh_co2: 702},
    "MLT": {name: "Malta", conv_kwh_co2: 652},
    "MHL": {name: "Marshall Islands"},
    "MTQ": {name: "Martinique"},
    "MRT": {name: "Mauritania", conv_kwh_co2: 687},
    "MUS":{name: "Mauritius", conv_kwh_co2: 651},
    "MYT":{name: "Mayotte"},
    "MEX":{name: "Mexico", conv_kwh_co2: 450},
    "FSM": {name: "Micronesia, Federated States of"},
    "MDA":{name: "Moldova, Republic of", conv_kwh_co2: 503},
    "MCO":{name: "Monaco"},
    "MNG": {name: "Mongolia", conv_kwh_co2: 1272},
    "MNE":{name: "Montenegro", conv_kwh_co2: 830},
    "MSR":{name: "Montserrat"},
    "MAR":{name: "Morocco", conv_kwh_co2: 612},
    "MOZ":{name: "Mozambique", conv_kwh_co2: 172},
    "MMR": {name: "Myanmar", conv_kwh_co2: 518},
    "NAM": {name: "Namibia", conv_kwh_co2: 195},
    "NRU": {name: "Nauru"},
    "NPL": {name: "Nepal", conv_kwh_co2: 16},
    "NLD":{name: "Netherlands", conv_kwh_co2: 280},
    "ANT": {name: "Netherlands Antilles"},
    "NCL":{name: "New Caledonia", conv_kwh_co2: 652},
    "NZL": {name: "New Zealand", conv_kwh_co2: 235},
    "NIC": {name: "Nicaragua", conv_kwh_co2: 606},
    "NER": {name: "Niger", conv_kwh_co2: 761},
    "NGA": {name: "Nigeria", conv_kwh_co2: 477},
    "NIU": {name: "Niue"},
    "NFK":{name: "Norfolk Island"},
    "MNP": {name: "Northern Mariana Islands"},
    "NOR": {name: "Norway", conv_kwh_co2: 55},
    "OMN": {name: "Oman", conv_kwh_co2: 494},
    "PAK": {name: "Pakistan", conv_kwh_co2: 594},
    "PLW": {name: "Palau"},
    "PSE": {name: "Palestinian Territory, Occupied"},
    "PAN": {name: "Panama", conv_kwh_co2: 551},
    "PNG": {name: "Papua New Guinea"},
    "PRY": {name: "Paraguay", conv_kwh_co2: 16},
    "PER": {name: "Peru", conv_kwh_co2: 424},
    "PHL": {name: "Philippines", conv_kwh_co2: 543},
    "PCN":{name: "Pitcairn"},
    "POL": {name: "Poland", conv_kwh_co2: 765},
    "PRT": {name: "Portugal", conv_kwh_co2: 366},
    "PRI": {name: "Puerto Rico"},
    "QAT": {name: "Qatar"},
    "REU": {name: "Reunion"},
    "ROU": {name: "Romania", conv_kwh_co2: 455},
    "RUS": {name: "Russian Federation", conv_kwh_co2: 461},
    "RWA":{name: "Rwanda", conv_kwh_co2: 643},
    "SHN":{name: "Saint Helena"},
    "KNA":{name: "Saint Kitts and Nevis", conv_kwh_co2: 684},
    "LCA":{name: "Saint Lucia", conv_kwh_co2: 706},
    "SPM":{name: "Saint Pierre and Miquelon"},
    "VCT":{name: "Saint Vincent and the Grenadines", conv_kwh_co2: 691},
    "WSM":{name: "Samoa", conv_kwh_co2: 667},
    "SMR":{name: "San Marino"},
    "STP":{name: "Sao Tome and Principe", conv_kwh_co2: 694},
    "SAU":{name: "Saudi Arabia", conv_kwh_co2: 650},
    "SEN":{name: "Senegal", conv_kwh_co2: 674},
    "SRB":{name: "Serbia", conv_kwh_co2: 938},
    "SYC":{name: "Seychelles"},
    "SLE":{name: "Sierra Leone", conv_kwh_co2: 641},
    "SGP":{name: "Singapore"},
    "SVK":{name: "Slovakia", conv_kwh_co2: 285},
    "SVN": {name: "Slovenia", conv_kwh_co2: 536},
    "SLB":{name: "Solomon Islands", conv_kwh_co2: 732},
    "SOM": {name: "Somalia"},
    "ZAF": {name: "South Africa", conv_kwh_co2: 1008},
    "SGS": {name: "South Georgia and the South Sandwich Islands"},
    "ESP": {name: "Spain", conv_kwh_co2: 342},
    "LKA":{name: "Sri Lanka", conv_kwh_co2: 615},
    "SDN": {name: "Sudan", conv_kwh_co2: 530},
    "SUR": {name: "Suriname", conv_kwh_co2: 741},
    "SJM":{name: "Svalbard and Jan Mayen"},
    "SWZ": {name: "Swaziland", conv_kwh_co2: 16},
    "SWE": {name: "Sweden", conv_kwh_co2: 60},
    "CHE":{name: "Switzerland", conv_kwh_co2: 39},
    "SYR": {name: "Syrian Arab Republic"},
    "TWN": {name: "Taiwan", conv_kwh_co2: 482},
    "TJK": {name: "Tajikistan", conv_kwh_co2: 57},
    "TZA": {name: "Tanzania, United Republic of", conv_kwh_co2: 620},
    "THA": {name: "Thailand", conv_kwh_co2: 428},
    "TLS": {name: "Timor-Leste", conv_kwh_co2: 732},
    "TGO": {name: "Togo", conv_kwh_co2: 527},
    "TKL": {name: "Tokelau"},
    "TON": {name: "Tonga"},
    "TTO": {name: "Trinidad and Tobago", conv_kwh_co2: 561},
    "TUN": {name: "Tunisia", conv_kwh_co2: 470},
    "TUR": {name: "Turkey", conv_kwh_co2: 360},
    "TKM": {name: "Turkmenistan", conv_kwh_co2: 850},
    "TCA": {name: "Turks and Caicos Islands"},
    "TUV": {name: "Tuvalu"},
    "UGA": {name: "Uganda", conv_kwh_co2: 201},
    "UKR": {name: "Ukraine", conv_kwh_co2: 738},
    "ARE": {name: "United Arab Emirates", conv_kwh_co2: 522},
    "GBR": {name: "United Kingdom", conv_kwh_co2: 358},
    "USA":{name: "United States", conv_kwh_co2: 418} ,
    "UMI": {name: "United States Minor Outlying Islands"},
    "URY": {name: "Uruguay", conv_kwh_co2: 237},
    "UZB": {name: "Uzbekistan", conv_kwh_co2: 610},
    "VUT":{name: "Vanuatu", conv_kwh_co2: 634},
    "VEN": {name: "Venezuela", conv_kwh_co2: 534},
    "VNM": {name: "Vietnam", conv_kwh_co2: 385},
    "VGB": {name: "Virgin Islands, British"},
    "VIR": {name: "Virgin Islands, U.S."},
    "WF": {name: "Wallis and Futuna"},
    "ESH": {name: "Western Sahara"},
    "YEM":{name: "Yemen", conv_kwh_co2: 724},
    "ZMB": {name: "Zambia", conv_kwh_co2: 129},
    "ZWE": {name: "Zimbabwe", conv_kwh_co2: 1302}
}



//convert g to kg
Object.values(Countries).forEach(c=>{
    c.conv_kwh_co2 /= 1000;
});


module.exports = Countries